import Image from 'next/image';
import React from 'react';

export default function Invoices() {
  // const [invoiceList, setInvoiceList] = useState([]);
  const invoiceList = [];

  return (
    <div>
      {invoiceList.length === 0 && (
        <div className='flex flex-col items-center justify-center'>
          <Image
            src='/assets/svg/invoices.svg'
            alt='invoices'
            width={227}
            height={128}
            className='mt-[170px]'
          />
          <div className='text-dark-normal mb-[14px] mt-[45px] text-2xl font-medium'>
            No Invoices have been generated yet
          </div>
          <div className='text-gray-80'>
            Invoices will be created automatically based on the query fees
            generated by your API keys
          </div>
        </div>
      )}
    </div>
  );
}
