import type { TableColumnsType } from 'antd';
import { Table, Tag } from 'antd';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';

import { useDebounceCallback } from '@/lib/utils';

import Copy from '@/components/Copy';

import { getInvoices } from '@/api/requestMarket';

import { InvoicesItem } from '@/types/marketType';

export default function Invoices() {
  const [invoiceList, setInvoiceList] = useState<InvoicesItem[]>([]);
  const isMobile = window?.innerWidth < 640;

  const getInvoicesList = useDebounceCallback(async () => {
    const { items } = await getInvoices();
    setInvoiceList(items);
  }, []);

  useEffect(() => {
    getInvoicesList();
  }, [getInvoicesList]);

  const columns: TableColumnsType = [
    {
      title: 'Invoice No.',
      dataIndex: 'billingId',
      key: 'billingId',
      render: (text: string) => (
        <div>
          <Copy label='' content={text} isShowCopy={true} showLittle={true} />
        </div>
      ),
    },
    {
      title: 'Date Issued',
      dataIndex: 'billingDate',
      key: 'billingDate',
    },
    {
      title: 'Billing Period',
      dataIndex: 'billingStartDate',
      key: 'billingStartDate',
    },
    {
      title: 'Due Date',
      dataIndex: 'billingEndDate',
      key: 'billingEndDate',
    },
    {
      title: 'Amount',
      dataIndex: 'billingAmount',
      key: 'billingAmount',
      render: (text: number) => (
        <div>
          {text}
          <span className='ml-[4px] text-sm'>USDT</span>
        </div>
      ),
    },
    {
      title: 'Status',
      dataIndex: 'billingStatus',
      key: 'billingStatus',
      render: (text: number) => {
        return (
          <div>
            {text === 0 && <Tag color='#FF9900'>PendingPayment</Tag>}
            {text === 1 && <Tag color='green'>Paid</Tag>}
            {text === 2 && <Tag color='red'>PartiallyPaid</Tag>}
          </div>
        );
      },
    },
    {
      title: 'TransactionState',
      dataIndex: 'transactionState',
      key: 'transactionState',
      render: (text: string) => (
        <div>
          {text === 'NOTEXISTED' && <Tag color='#FF9900'>NOTEXISTED</Tag>}
          {text === 'MINED' && <Tag color='green'>MINED</Tag>}
          {text === 'FAILED' && <Tag color='red'>FAILED</Tag>}
        </div>
      ),
    },
  ];

  return (
    <div>
      {invoiceList.length === 0 && (
        <div className='flex flex-col items-center justify-center'>
          <Image
            src='/assets/svg/invoices.svg'
            alt='invoices'
            width={227}
            height={128}
            className='mt-[170px]'
          />
          <div className='text-dark-normal mb-[14px] mt-[45px] text-2xl font-medium'>
            No Invoices have been generated yet
          </div>
          <div className='text-gray-80'>
            Invoices will be created automatically based on the query fees
            generated by your API keys
          </div>
        </div>
      )}
      {invoiceList.length > 0 && (
        <div className='mt-[4px]'>
          <Table
            rowKey='id'
            columns={columns}
            dataSource={invoiceList}
            className='w-full'
            size={isMobile ? 'small' : 'middle'}
            pagination={false}
            scroll={{ x: 'max-content' }}
          />
        </div>
      )}
    </div>
  );
}
